Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/05/2022
Var
// Seção de Declarações das variáveis 
 lin  : inteiro
 col :  inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para lin de 1 ate 9
  para col de 1 ate 9
    se

Fimalgoritmo